export interface FaqItem {
  question: string
  answer: string
}

export const faqData: Record<string, FaqItem[]> = {
  "what-is-good-mrr-growth-rate": [
    { question: "What is a good MRR growth rate for early-stage SaaS?", answer: "Pre-seed/Seed ($0-$10K MRR): 20-30%+ MoM. Early traction ($10K-$50K MRR): 15-25% MoM. Growth stage ($50K-$200K MRR): 10-20% MoM. Scale ($200K-$1M MRR): 5-10% MoM. Mature ($1M+ MRR): 3-7% MoM." },
    { question: "How do you calculate MRR growth rate?", answer: "MRR Growth Rate = ((MRR This Month - MRR Last Month) / MRR Last Month) x 100. Always use this formula rather than eyeballing charts. Track month-over-month, year-over-year, and trailing 3-month and 6-month averages to smooth volatility." },
    { question: "Why is raw MRR growth rate misleading?", answer: "A 15% MoM growth rate can hide serious problems. You need to decompose MRR into new, expansion, contraction, and churned components. If you are adding $10K new MRR but losing $4.5K to churn, your net growth looks good but you are on a treadmill." },
    { question: "What is the Rule of 40 for SaaS?", answer: "The Rule of 40 states that MRR Growth Rate % + Profit Margin % should equal 40 or higher. For example, growing at 15% MoM with -30% margins gives you -15, well below the threshold. Pre-seed focuses on growth; Series A balances both." },
    { question: "What kills MRR growth for SaaS companies?", answer: "Five common killers: (1) high churn eating new MRR, (2) no expansion revenue (below 10% of net new MRR), (3) growth plateaus after acquisition spikes, (4) pricing too low (avg contract under $100/month for B2B), and (5) inefficient acquisition channels with LTV:CAC below 3:1." }
  ],
  "arr-vs-mrr-difference": [
    { question: "What is the difference between MRR and ARR?", answer: "MRR (Monthly Recurring Revenue) measures normalized monthly subscription revenue and is best for day-to-day operations. ARR (Annual Recurring Revenue) is MRR x 12 and is used for fundraising decks, board reporting, and company valuation." },
    { question: "When should you track MRR vs ARR?", answer: "Track MRR daily if you are pre-seed to Series A with ARR under $2M, iterating on pricing, or need early churn warnings. Track ARR monthly if you are Series A+, preparing for fundraising, reporting to a board, or comparing to public SaaS comps." },
    { question: "How do investors evaluate MRR and ARR?", answer: "Investors focus on three things: growth rate (is ARR growing 100%+ YoY?), efficiency (what is your magic number?), and retention (what is your NRR?). A $500K ARR company growing 15% MoM is more interesting than a $2M ARR company growing 5%." },
    { question: "Can ARR be misleading for growing companies?", answer: "Yes. ARR assumes zero growth over the year. If you are growing 10% month-over-month, your current ARR dramatically understates where you will be in 12 months. That is why growth-stage companies report ARR alongside growth rate." },
    { question: "What does NRR above 100% mean?", answer: "Net Revenue Retention above 100% means your existing customers are spending more over time, you would grow even with zero new customer acquisition. Above 120% is world-class and indicates strong product-market fit with organic expansion." }
  ],
  "how-to-calculate-saas-mrr": [
    { question: "What is the correct formula for SaaS MRR?", answer: "MRR = Active Subscribers x Average Revenue Per User (ARPU). For Net New MRR, combine new customer MRR, expansion MRR (upgrades), subtract churned MRR (cancellations), and subtract contraction MRR (downgrades)." },
    { question: "What should NOT be included in MRR?", answer: "Do not include one-time setup fees, professional services, annual plans counted as a single month payment, refunds, chargebacks, or gift card purchases. Only recurring subscription revenue counts toward MRR." },
    { question: "How do you count annual plans in MRR?", answer: "Divide the annual payment by 12. For example, a $1,188 annual plan represents $99/month in MRR. Never count the full annual payment as a single month MRR, this will artificially inflate your numbers." },
    { question: "Why do spreadsheets fail at MRR tracking?", answer: "Spreadsheets suffer from stale data, silent formula errors, no audit trail, and hours of manual busywork. They cannot handle recurring data at scale and are error-prone when customers churn mid-month or upgrade between periods." },
    { question: "What is a common MRR calculation mistake founders make?", answer: "The most common mistake is including one-time fees (like setup charges) as recurring revenue. Another frequent error is counting annual plan payments as a single month MRR instead of normalizing to monthly, and ignoring mid-month churn when customers cancel partway through a billing period." }
  ],
  "how-to-reduce-saas-churn": [
    { question: "What is a good monthly churn rate for B2B SaaS?", answer: "A healthy monthly churn rate for B2B SaaS is under 2%. Below 1% is excellent. Anything above 5% monthly needs immediate attention, it means you are losing more than 60% of your revenue base annually." },
    { question: "How much revenue does churn cost a SaaS company per year?", answer: "With 5% monthly churn on $100K MRR, you lose $5,000/month or approximately $46,000 per year (compounded). Reducing churn from 5% to 2% saves roughly $28,000 annually and requires 60% fewer new customers to maintain growth." },
    { question: "What is the single highest-leverage churn reduction strategy?", answer: "Switching high-churn customers to annual plans. Customers on annual plans churn at 2-4x lower rates than monthly subscribers. Offering a 15-20% annual discount improves both retention and upfront cash flow." },
    { question: "How do you build a customer health score?", answer: "Combine product usage data (login frequency, feature adoption), support ticket frequency, NPS responses, and payment history into a single score per customer. Segment into green (healthy), yellow (at-risk), and red (critical), and focus proactive outreach on yellow accounts." },
    { question: "When should a SaaS company focus on churn vs. acquisition?", answer: "Focus on churn first if monthly churn exceeds 3% or if more than 20% of new customers churn within the first 90 days. Improving retention compounds over time and is typically cheaper than acquiring new customers." }
  ],
  "saas-unit-economics-guide": [
    { question: "What is the ideal LTV:CAC ratio for SaaS?", answer: "The target LTV:CAC ratio for SaaS is 3:1 or higher. A ratio below 2:1 means you are spending too much to acquire customers relative to their lifetime value. Above 5:1 is excellent and suggests room to invest more aggressively in growth." },
    { question: "How do you calculate SaaS customer lifetime value (LTV)?", answer: "LTV = ARPA x Gross Margin / Monthly Churn Rate. For example, with $100/month ARPA, 80% gross margin, and 5% monthly churn, LTV = $100 x 0.80 / 0.05 = $1,600." },
    { question: "What is a good CAC payback period?", answer: "A CAC payback period under 6 months is excellent, 6-12 months is good, 12-18 months is acceptable for enterprise SaaS, and over 18 months is risky as it ties up capital. Shorter payback allows faster reinvestment and growth." },
    { question: "What is a good SaaS quick ratio?", answer: "A SaaS quick ratio above 4 indicates exceptional growth, 2-4 is healthy, and below 2 suggests slow growth. The quick ratio = (New MRR + Expansion MRR) / (Churned MRR + Contraction MRR)." },
    { question: "What is the magic number in SaaS?", answer: "The magic number measures sales efficiency: Magic Number = Net New ARR (current quarter) / Sales and Marketing Spend (previous quarter). Above 0.75 is good, and above 1.0 is excellent, indicating you are acquiring customers efficiently." }
  ],
  "saas-financial-metrics-founders": [
    { question: "What are the 10 most important SaaS financial metrics?", answer: "The 10 essential metrics are: MRR, ARR, MRR Growth Rate, Churn Rate, Customer Lifetime Value (LTV), Customer Acquisition Cost (CAC), Net Revenue Retention (NRR), Burn Rate, Runway, and Gross Margin." },
    { question: "What is a good LTV:CAC ratio for SaaS?", answer: "The target LTV:CAC ratio is 3:1 or higher. Below 1:1 means you are losing money on every customer. 1:1 to 2:1 is unsustainable. 3:1 is the industry benchmark. 5:1+ is excellent with room to invest aggressively in growth." },
    { question: "What is Net Revenue Retention and why does it matter?", answer: "NRR measures revenue retained from existing customers including expansion. NRR = (Starting MRR - Churn - Contraction + Expansion) / Starting MRR x 100. Below 100% means shrinking, 100-120% is healthy, and 120%+ is excellent with negative net churn." },
    { question: "How do you calculate burn rate for a SaaS company?", answer: "Net Burn = Monthly Expenses - Monthly Revenue. Burn rate determines your runway: Runway = Cash Balance / Net Burn Rate. Always maintain 18+ months of runway, especially if planning to raise funding." },
    { question: "What is a good gross margin for SaaS?", answer: "Target 80%+ gross margin for SaaS. Below 60% is low (infrastructure-heavy), 60-70% is average, 70-80% is good, and 80%+ is excellent. Gross margin = (Revenue - COGS) / Revenue x 100, where COGS includes hosting, payment processing, and support costs." }
  ],
  "saas-churn-rate-guide": [
    { question: "What is a good monthly churn rate for B2B SaaS?", answer: "A good monthly churn rate for B2B SaaS is 3-5% (good), 1-2% (great), or below 1% (elite). For revenue churn, below 2-3% monthly is good, under 1% is great, and negative net churn (where expansion exceeds churn) is elite." },
    { question: "How do you calculate monthly vs annual churn rate?", answer: "Monthly churn = (Customers Lost) / (Customers at Start of Month) x 100. Annual churn is NOT monthly x 12, it compounds: Annual Churn = 1 - (1 - Monthly Churn)^12. So 3% monthly churn becomes 31% annual churn, not 36%." },
    { question: "What are the most effective ways to reduce SaaS churn?", answer: "The 7 most effective tactics are: fix onboarding to reach the aha moment quickly, identify at-risk accounts early via usage signals, offer annual plans with a discount, build engagement loops, make cancellation painless then fix the reason, implement save flows, and measure health scores." },
    { question: "When is high churn acceptable for a SaaS startup?", answer: "Pre-product-market-fit startups may see 5-10% monthly churn. Focus on finding the right customer segment rather than obsessing over churn numbers. Once past PMF, monthly churn above 5% is a crisis that needs immediate attention." },
    { question: "How does churn impact SaaS revenue over time?", answer: "Churn compounds. At 5% monthly churn, you lose approximately 46% of your revenue base annually. Reducing churn from 5% to 2% saves roughly $28,000 per year on a $100K MRR base and requires 60% fewer new customers to maintain growth." }
  ],
  "mrr-dashboard-guide": [
    { question: "What is an MRR dashboard?", answer: "An MRR dashboard is a real-time analytics view that automatically tracks your Monthly Recurring Revenue and related metrics: new MRR, expansion MRR, contraction MRR, churned MRR, and net new MRR, pulling data directly from your payment processor like Stripe or PayPal." },
    { question: "How often should you check your MRR dashboard?", answer: "Check your MRR dashboard at least weekly. Daily monitoring helps you spot churn spikes and expansion opportunities before they compound. Real-time visibility allows you to react to problems faster than monthly reviews." },
    { question: "What is the difference between MRR and ARR?", answer: "MRR (Monthly Recurring Revenue) is your normalized monthly subscription revenue. ARR (Annual Recurring Revenue) is MRR x 12, representing the annualized run-rate. Use MRR for day-to-day operational tracking and ARR for fundraising and board reporting." },
    { question: "Why does Stripe built-in MRR report show inaccurate numbers?", answer: "Stripe calculates MRR from subscription objects, not paid invoices. This causes errors with annual plan normalization, free trials appearing as revenue, discount period inflation, and multi-currency fluctuations. A dedicated MRR dashboard calculates from actual paid invoices." },
    { question: "What MRR metrics should an MRR dashboard include?", answer: "An effective MRR dashboard should show: Total MRR, New MRR, Expansion MRR, Contraction MRR, Churned MRR, Net New MRR, MRR growth rate, churn rate, ARPU, LTV, and a trend chart. Cash flow forecasting and cohort retention views add further operational value." }
  ],
  "saas-cash-flow-management": [
    { question: "How much cash runway should a SaaS startup have?", answer: "Maintain at least 12 months of cash runway at all times. If you are planning to raise funding, extend to 18+ months to give yourself enough time to close a round without desperation-driven dilution." },
    { question: "What is a healthy burn rate for a SaaS company?", answer: "Net burn should be under 10% of your cash balance per month. More importantly, track your burn multiple: spending under $1 to generate $1 of new ARR is strong. A burn multiple above 2x indicates inefficient spending." },
    { question: "How do you build a 90-day cash flow forecast for SaaS?", answer: "Start with your cash position, project revenue inflows (MRR x growth rate minus churn), project cash outflows (payroll, infrastructure, marketing, tools), calculate the monthly cash position, and run three scenarios: base, downside (30% slower growth + 50% higher churn), and upside." },
    { question: "When should a SaaS company raise funding vs cut costs?", answer: "Raise if growth is strong (20%+ monthly MRR), the market is large, and you have 12-18 months to close a round. Cut if growth has slowed below 10% monthly, you have not found product-market fit, or you can reach profitability by reducing burn." },
    { question: "Why does high growth sometimes create cash flow problems in SaaS?", answer: "Growth accelerates spending, you pay for marketing and sales before customers generate revenue. A $1,200/year customer only pays $100/month, so revenue is delayed while acquisition costs are front-loaded. CAC payback periods of 12-18 months are common." }
  ],
  "stripe-mrr-dashboard-for-founders": [
    { question: "Why is Stripe built-in MRR report inaccurate?", answer: "Stripe calculates MRR from subscription objects rather than paid invoices. This causes systematic errors: annual plans may not be correctly normalized, free trials appear as revenue, discount coupons inflate MRR during the discount period, and multi-currency fluctuations move your reported MRR." },
    { question: "What is Net Revenue Retention (NRR) and why does it matter?", answer: "NRR measures revenue retained from existing customers including expansion, contraction, and churn. NRR = (Starting MRR + Expansion - Contraction - Churn) / Starting MRR x 100. Above 100% means existing customers pay more over time. Above 120% is world-class." },
    { question: "How do you set up an accurate Stripe MRR dashboard?", answer: "Connect your Stripe account to a dedicated MRR tool like AI Finance Ops via OAuth. It automatically backfills up to 24 months of historical data and calculates MRR from actual paid invoices, not subscription objects, giving you accurate numbers with no manual work." },
    { question: "What 6 metrics should a Stripe MRR dashboard include?", answer: "Total MRR, MRR Growth Rate, New MRR, Expansion MRR, Churned MRR, and Net Revenue Retention (NRR). These give you a complete picture of revenue health, from acquisition momentum to expansion quality to customer retention." },
    { question: "How should founders use their MRR dashboard operationally?", answer: "Weekly: check the MRR waterfall for churn acceleration. Monthly: review cohort retention to see which signup cohorts retained best. Quarterly: calculate NRR for investor updates. Annually: use the 24-month MRR trend for financial projections and fundraising narratives." }
  ],
  "how-to-build-saas-financial-model": [
    { question: "What should a SaaS financial model include?", answer: "A SaaS financial model should include revenue projections (MRR/ARR growth), expense forecasting (team, tools, marketing), cash flow planning (when you will be profitable or need funding), and scenario analysis (best case, worst case, base case)." },
    { question: "What are the key assumptions in a SaaS financial model?", answer: "Key assumptions include current MRR, monthly growth rate, churn rate, expansion rate, pricing per tier, team size and salaries, tools and infrastructure costs, marketing spend, trial-to-paid conversion rate, and average revenue per account (ARPA)." },
    { question: "How do you project monthly revenue in a SaaS model?", answer: "Month N MRR = Previous Month MRR x (1 + Growth Rate) - Churned MRR + Expansion MRR. New MRR = Previous MRR x Growth Rate, Expansion MRR = Previous MRR x Expansion Rate (typically 2-5%), and Churned MRR = Previous MRR x Churn Rate." },
    { question: "What are common mistakes when building a SaaS financial model?", answer: "Common mistakes include over-optimistic growth projections, forgetting to account for churn (which compounds over time), ignoring seasonality, not updating the model monthly, and relying on a single scenario instead of modeling best/worst/base cases." },
    { question: "How often should you update your SaaS financial model?", answer: "Update your financial model monthly with actual data. A model is only useful if it reflects current reality, stale assumptions lead to bad decisions. Revisit assumptions quarterly and run new scenario analyses whenever market conditions change." }
  ],
  "saas-metrics-for-investors": [
    { question: "What metrics do SaaS investors care about most?", answer: "Investors prioritize: MRR/ARR and growth rate (traction), LTV:CAC ratio and payback period (efficiency), Net Revenue Retention (expansion), churn rate (retention), and gross margin (unit economics). The weight changes by stage: early focuses on growth, later stages on efficiency." },
    { question: "What ARR growth rate do investors expect by stage?", answer: "Pre-seed: 15-20% MoM (100-200%+ YoY). Seed: 15-20% MoM. Series A: 10-15% MoM (3x+ YoY). Series B: 8-12% MoM (2-3x YoY). Growth: 5-10% MoM (2x+ YoY). Late stage: 3-7% MoM with strong profitability metrics." },
    { question: "What is a good LTV:CAC ratio for fundraising?", answer: "Target 3:1 or higher. Below 2:1 is a red flag. Above 5:1 suggests you are under-investing in growth. Payback under 12 months is good; under 6 months is excellent. Investors will calculate these independently, so know your numbers." },
    { question: "What is the Rule of 40 and do investors use it?", answer: "The Rule of 40: Growth Rate % + Profit Margin % >= 40. It is a quick sanity check. Growth-stage companies often trade growth for profitability. A company growing 30% with 10% margins scores 40, which is borderline. Growth matters more at earlier stages." },
    { question: "How should founders present SaaS metrics to investors?", answer: "Lead with a one-page metrics summary showing MRR, growth rate, churn, LTV:CAC, NRR, and burn rate. Show 12-24 month trends, not just current snapshots. Include cohort retention charts and MRR decomposition. Be honest about challenges and show your plan to address them." }
  ]
}
